data_catalog: C:\Users\berg\Documents\GitHub\UFFFS-East-Africa\config\data_catalog.yml

cities:
  Addis:
    wflow: 
      enabled: false
    sfincs:
      addis_sfincsmodel_01:
        region: cities/Addis/data/sfincs_domains/Basin1_dissolved.geojson
        build_config: config/templates/sfincs/build_base.yml
        build_overrides: cities/Addis/params/sfincs/addis_sfincsmodel_01.yml
        model_dir: outputs/Addis/sfincs/addis_sfincsmodel_01/base
      addis_sfincsmodel_02:
        region: cities/Addis/data/sfincs_domains/Basin2_dissolved.geojson
        build_config: config/templates/sfincs/build_base.yml
        build_overrides: cities/Addis/params/sfincs/addis_sfincsmodel_02.yml
        model_dir: outputs/Addis/sfincs/addis_sfincsmodel_02/base

  # Kampala:
  #   wflow:
  #     enabled: false
  #   sfincs:
  #     kampala_sfincsmodel_01:
  #       region: cities/Kampala/data/sfincs_domains/kampala_sfincsmodel_01.geojson
  #       build_config: config/templates/sfincs/build_base.yml
  #       build_overrides: cities/Kampala/params/sfincs/kampala_sfincsmodel_01.yml
  #       model_dir: outputs/Kampala/sfincs/kampala_sfincsmodel_01/base
  #     kampala_sfincsmodel_02:
  #       region: cities/Kampala/data/sfincs_domains/kampala_sfincsmodel_02.geojson
  #       build_config: config/templates/sfincs/build_base.yml
  #       build_overrides: cities/Kampala/params/sfincs/kampala_sfincsmodel_02.yml
  #       model_dir: outputs/Kampala/sfincs/kampala_sfincsmodel_02/base
  #     kampala_sfincsmodel_03:
  #       region: cities/Kampala/data/sfincs_domains/kampala_sfincsmodel_03.geojson
  #       build_config: config/templates/sfincs/build_base.yml
  #       build_overrides: cities/Kampala/params/sfincs/kampala_sfincsmodel_03.yml
  #       model_dir: outputs/Kampala/sfincs/kampala_sfincsmodel_03/base
  #     kampala_sfincsmodel_04:
  #       region: cities/Kampala/data/sfincs_domains/kampala_sfincsmodel_04.geojson
  #       build_config: config/templates/sfincs/build_base.yml
  #       build_overrides: cities/Kampala/params/sfincs/kampala_sfincsmodel_04.yml
  #       model_dir: outputs/Kampala/sfincs/kampala_sfincsmodel_04/base
# Juba:
#     wflow:
#       region: cities/Juba/data/wflow_basin.geojson
#       build_config: config/templates/wflow/build.yml
#       build_overrides: cities/Juba/params/wflow_overrides.yml

#     sfincs:
#       juba_sfincsmodel_01:
#         region: cities/Juba/data/sfincs_domains/juba_sfincsmodel_01.geojson
#         build_config: config/templates/sfincs/build_base.yml
#         build_overrides: cities/Juba/params/sfincs/juba_sfincsmodel_01.yml
#         model_dir: outputs/Juba/sfincs/juba_sfincsmodel_01/base

#       juba_sfincsmodel_02:
#         region: cities/Juba/data/sfincs_domains/juba_sfincsmodel_02.geojson
#         build_config: config/templates/sfincs/build_base.yml
#         build_overrides: cities/Juba/params/sfincs/juba_sfincsmodel_02.yml
#         model_dir: outputs/Juba/sfincs/juba_sfincsmodel_02/base

#       submodel_03:
#         region: cities/Juba/data/sfincs_domains/juba_sfincsmodel_03.geojson
#         build_config: config/templates/sfincs/build_base.yml
#         build_overrides: cities/Juba/params/sfincs/submodel_03.yml
#         model_dir: outputs/Juba /sfincs/submodel_03/base
