copdem30:
  data_type: RasterDataset
  uri: topography/copdem/copdem.vrt
  driver:
    name: rasterio
    options:
      chunks:
        x: 3600
        y: 3600
  data_adapter:
    rename:
      copdem: elevtn
  metadata:
    nodata: -9999
    category: topography
    source_license: https://spacedata.copernicus.eu/documents/20126/0/CSCDA_ESA_Mission-specific+Annex+%281%29.pdf/83b44c0a-244a-7ba3-b00c-b578a34e88a7?t=1604070311399
    source_url: https://spacedata.copernicus.eu/web/cscda/dataset-details?articleId=394198#D4
    source_version: 2021_1


# kampala_05m_dem_lidar:
#   data_type: RasterDataset
#   uri: cities/Kampala/data/Kampala_dem_05m_v1.tif
#   driver: 
#     name: rasterio
#     options:
#       chunks:
#         x: 3600
#         y: 3600
#   metadata:
#     category: topography
#     # nodata: -9999  # copdem has no actual nodata, this is to suppress a missing nodata warning 

esa_worldcover2021:
  data_type: RasterDataset
  uri: esa-worldcover.tif
  driver:
    name: rasterio
    options:
      chunks:
        x: 36000
        y: 36000
  metadata:
    crs: 4326
    category: landuse
    source_license: CC BY 4.0
    source_url: https://doi.org/10.5281/zenodo.5571936
    source_version: v100

# merit_hydro:
#   data_type: RasterDataset
#   uri: topography/merit_hydro_data/*.vrt
#   driver:
#     name: rasterio
#     options:
#       chunks:
#         x: 6000
#         y: 6000
#   data_adapter:
#     rename:
#       bas: basins
#       dir: flwdir
#       elv: elevtn
#       slp: lndslp
#       sto: strord
#       upa: uparea
#       upg: upgrid
#       wth: rivwth
#   metadata:
#     crs: 4326
#     category: topography
#     paper_doi: 10.1029/2019WR024873
#     paper_ref: Yamazaki et al. (2019)
#     source_license: CC-BY-NC 4.0 or ODbL 1.0
#     source_url: http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro
#     source_version: 1.0
