global:
  data_libs: 'deltares_data'
  sfincs_exe: "c:/Program Files/Deltares/SFINCS_v2.3.0_mt_Faber_release_exe/sfincs.exe"

cities:
  Kampala:
    events:
      era5_may2024:
        start: "20200501 000000"
        end: "20200503 000000"
        models: 
          - kampala_sfincsmodel_01_lidar
        forcing:
          type: catalog
          precip: "era5_hourly"
        postprocess:
          hmin: 0.05
      synthetic_60mm_6h:
        start: "20240601 000000"
        end: "20240601 060000"
        models: all
        forcing:
          type: synthetic_constant
          precipitation_mm_per_hr: 10
        postprocess:
          hmin: 0.05
      # synthetic_100mm_24h:
      #   start: "20240601 000000"
      #   end: "20240601 030000"
      #   models:
      #     - kampala_sfincsmodel_01_lidar
      #   forcing:
      #     type: synthetic_constant
      #     precipitation_mm_per_hr: 4.1666667
      #   postprocess:
      #     hmin: 0.05